### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Provider'   on Faker()

### ISSUE THREAD

**Issue by aldarund** [joke2k/faker#332]
When i create a Faker class i got following error:

`````` ======================================================================
ERROR: Failure: AttributeError ('module' object has no attribute 'Provider')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/rentapplication/django-rentapplication/rentapplication/tests/test_api/test_sessions.py", line 10, in <module>
    from rentapplication.tests.helpers import ReferrerFactory, LandlordFactory
  File "/home/rentapplication/django-rentapplication/rentapplication/tests/helpers.py", line 35, in <module>
    f = Faker()
  File "/usr/local/lib/python2.7/dist-packages/faker/factory.py", line 38, in create
    prov_cls, lang_found = cls._get_provider_class(prov_name, locale)
  File "/usr/local/lib/python2.7/dist-packages/faker/factory.py", line 49, in _get_provider_class
    provider_class = cls._find_provider_class(provider, locale)
  File "/usr/local/lib/python2.7/dist-packages/faker/factory.py", line 87, in _find_provider_class
    return provider_module.Provider
AttributeError: 'module' object has no attribute 'Provider'```
``````

**Comment by EnTeQuAk** [comment]
This happened most recently in the 0.5.4 release and only in the wheel package. Somehow the locales get moved into the `providers` folder:

```
/Downloads/ff/faker/providers> ls
address/    color.py        currency/     el_GR/  fa_IR/   __init__.py  ko_KR/    miscelleneous.py  phone_number/    python/    user_agent/
address.py  company/        currency.py   en_CA/  fi_FI/   internet/    lorem/    misc.py           phone_number.py  python.py  user_agent.py
barcode/    company.py      date_time/    en_GB/  file/    internet.py  lorem.py  nl_NL/            pl_PL/           ru_RU/     zh_CN/
barcode.py  credit_card/    date_time.py  en_US/  file.py  it_IT/       lt_LT/    no_NO/            profile/         sl_SI/     zh_TW/
bg_BG/      credit_card.py  de_DE/        es_ES/  fr_FR/   job/         lv_LV/    person/           profile.py       ssn/
color/      cs_CZ/          dk_DK/        es_MX/  hi_IN/   job.py       misc/     person.py         pt_BR/           ssn.py
```

The tar.gz file is fine.

**Comment by EnTeQuAk** [comment]
I also created a clean wheel package on my machine and it's clean, without the locale packages in the `providers` module. So maybe a new build + upload could fix this @joke2k 

As a workaround for everyone else stumbling on this, try installing it from the tar.gz package - this one works fine.

**Comment by smira** [comment]
+1, same problem, code is broken with 0.5.4

**Comment by strife25** [comment]
+1 on this issue

**Comment by fcurella** [comment]
I can confirm the issue.

Sadly I don't have access to PyPI and I can't fix the release. We'll have to wait for @joke2k to be back.

Please avoid adding more '+1' comments, as they don't add much to the conversation. We are aware of the issue and it will be fixed ASAP.

**Comment by farshidce** [comment]
File "/Users/farshid/flab/careabout/server/env/lib/python3.5/site-packages/faker/factory.py", line 87, in _find_provider_class
    return provider_module.Provider
AttributeError: module 'faker.providers.bg_BG' has no attribute 'Provider'
+1 on this issue.

and the issue was resolved by using 0.5.3 for the time being.

**Comment by fcurella** [comment]
I'm going to temporarily lock this issue to avoid +1 comments. Sorry for the inconvenience.

**Comment by fcurella** [comment]
We just released v0.0.5. Let us know if there's any issue!

Thank you all for your patience, very much appreciated! :sparkles:

**Comment by aluminiumgeek** [comment]
Please reopen the issue. I still get this error, even if installing Faker from `master`. The traceback is exactly the same as in original post.

**Comment by fcurella** [comment]
@aluminiumgeek can you provide a snippet of code that triggers the error, so I can try to reproduce?

**Comment by KarimJedda** [comment]
This is not reproducible when using a virtualenv. 
Tried both python setup.py install ad pip install faker in fresh venv's and it worked.

Maybe include a pip freeze as well? Some library could be somehow intefering..

**Comment by whit537** [comment]
> This is not reproducible when using a virtualenv.

Are you sure that's the variable? Does it fail for you if you use your system Python on the same system that you're trying with a virtualenv?

From @EnTeQuAk's comments above it sounds like the problem is with locales. I have not yet reproduced this problem locally, but we are seeing it at Travis, which I believe has limited locales installed (cf. https://github.com/travis-ci/travis-ci/issues/2598).

**Comment by whit537** [comment]
I've [confirmed](https://github.com/gratipay/gratipay.com/pull/4224#issuecomment-265513919) that the failure is attended by a wild `en_US` submodule appearing in `faker/providers/`. Nothing jumps out at me [in 0.5.4](https://github.com/joke2k/faker/compare/v0.5.3...v0.5.4) to suggest why the behavior was introduced there. Hmm ...

**Comment by fcurella** [comment]
@whit537 I don't see any `en_US` module in `faker/providers/` https://github.com/joke2k/faker/tree/v0.7.3/faker/providers

**Comment by whit537** [comment]
Using Travis's caching feature with `env/lib/python2.7/site-packages` [seems](https://github.com/gratipay/gratipay.com/pull/4224#issuecomment-265521291) to be a consistent predictor of failure in our environment. But ... what the h*ck to do with Travis caching is creating the additional files in `faker/providers/`? :thinking:

![screen shot 2016-12-07 at 1 45 43 pm](https://cloud.githubusercontent.com/assets/134455/20981618/7b0ec754-bc83-11e6-9520-ebafe8b2941b.png)

**Comment by whit537** [comment]
Okay! I think I figured it out: Travis [has](https://docs.travis-ci.com/user/caching/#Fetching-and-storing-caches) layered caching.

> If a branch does not have its own cache, Travis CI fetches the default branch cache.

My hypothesis is that one of the cache layers had an old library layout with the rogue files in place. Installing the new version over the old resulted in both sets of files being present. This hypothesis is confirmed in that [clearing](https://docs.travis-ci.com/user/caching/#Clearing-Caches) _all_ caches at Travis [seems](https://github.com/gratipay/gratipay.com/pull/4224#issuecomment-265540007) to have fixed the issue for us.

YMMV. Good luck! :-) 👍

**Comment by glassresistor** [comment]
I'm getting this trying to run it on AWS lambda as well.

**Comment by fcurella** [comment]
should be fixed in #649

**Comment by Kazanz** [comment]
Having same problem with Faker-0.8.10

**Comment by Oxicode** [comment]
+1

**Comment by aramanath** [comment]
I get this error with python-testdata and Faker:

```
$ python
Python 3.7.2 (default, Jan 13 2019, 12:50:15) 
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import testdata
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ajithr/kinesis/lib/python3.7/site-packages/testdata/__init__.py", line 7, in <module>
    from .factories.fake import *
  File "/Users/ajithr/kinesis/lib/python3.7/site-packages/testdata/factories/fake.py", line 5, in <module>
    class FakeDataFactory(Callable):
  File "/Users/ajithr/kinesis/lib/python3.7/site-packages/testdata/factories/fake.py", line 7, in FakeDataFactory
    _FAKER_FACTORY = faker.Factory.create()
  File "/Users/ajithr/kinesis/lib/python3.7/site-packages/faker/factory.py", line 58, in create
    prov_cls, lang_found = cls._get_provider_class(prov_name, locale)
  File "/Users/ajithr/kinesis/lib/python3.7/site-packages/faker/factory.py", line 69, in _get_provider_class
    provider_class = cls._find_provider_class(provider, locale)
  File "/Users/ajithr/kinesis/lib/python3.7/site-packages/faker/factory.py", line 130, in _find_provider_class
    return provider_module.Provider
AttributeError: module 'faker.providers.en_US' has no attribute 'Provider'
```

Versions info:

```
$ pip list
Package         Version
--------------- -------
fake-factory    0.2    
Faker           1.0.2  
pip             18.1   
python-dateutil 2.8.0  
python-testdata 1.0.5  
setuptools      40.6.2 
six             1.12.0 
text-unidecode  1.2    
```

**Comment by fcurella** [comment]
@aramanath The latest commit on [`python-testdata`](https://github.com/arieb/python-testdata) is from 2014. That makes me think it was written against an ancient version of `Faker`, probably `v0.4.2` or earlier. You should file an issue on `python-testdata`.
